### ISSUE TITLE
Notebook reset

### ISSUE THREAD

**Issue by eljirg** [udacity/cvnd-waffle-issues#10]
I did my project in udacity workspace, however to my surprise everything is empty this morning. 
Does the workspace save the files? Is it reset regularly?

**Comment by cgearhart** [comment]
I'm really sorry that you lost your work. 

The Workspace environment should save a copy of your home folder between sessions, but the home folder size is limited to about 5 GB. Data can be lost or corrupted (due to network connection timeout) when the folder grows too large. It is best to only store the files you need.

We just rolled out improved large file volume support for workspaces today. We will be transitioning all training data provided on the workspaces out of the home folders to improve reliability.
